os:
  - linux
language: node_js
node_js:
- 9
addons:
  apt:
    packages:
      - xvfb
      - libxtst-dev
      - libpng++-dev
before_install:
  - export DISPLAY=':99.0'
  - Xvfb :99 -screen 0 1024x768x24 > /dev/null 2>&1 &
before_script:
  - npm run setup-dev
script:
  - npm test
